mcpServers:
  netedge:
    command: ../gen-mcp/genmcp
    args:
      - run
      - -f
      - ../gen-mcp/examples/netedge-tools/mcpfile.yaml
      - -s
      - ../gen-mcp/examples/netedge-tools/mcpserver.yaml
    enableAllTools: true
