kind: Task
apiVersion: gevals/v1alpha2
metadata:
  name: "create-nginx-pod"
  difficulty: easy
spec:
  requires:
    - extension: kubernetes
  setup:
    - kubernetes.delete:
        apiVersion: v1
        kind: Namespace
        metadata:
          name: create-pod-test
    - kubernetes.create:
        apiVersion: v1
        kind: Namespace
        metadata:
          name: create-pod-test
  verify:
    - kubernetes.wait:
        apiVersion: v1
        kind: Pod
        metadata:
          name: web-server
          namespace: create-pod-test
        condition: Ready
        timeout: 120s
  cleanup:
    - kubernetes.delete:
        apiVersion: v1
        kind: Namespace
        metadata:
          name: create-pod-test
  prompt:
    inline: Please create a nginx pod named web-server in the create-pod-test namespace
